channels:
- conda-forge
dependencies:
- coverage
- graphviz =12.2.1
- owlrl =7.1.3
- numpy =2.2.3
- owlrl =7.1.3
- pint =0.24.4
- rdflib =7.1.4x
- pyshacl =0.30.1
- python >=3.10,<3.14
- python-graphviz =0.21
- setuptools =80.9.0
- typeguard=4.4.3
