channels:
- conda-forge
dependencies:
- coverage
- graphviz =12.2.1
- networkx =3.4.2
- numpy =2.3.1
- owlrl =7.1.4
- pint =0.25.0
- rdflib =7.1.4
- pyshacl =0.30.1
- python >=3.11,<3.14
- python-graphviz =0.21
- requests =2.32.5
- setuptools =80.9.0
- typeguard=4.4.4
