# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@actions-4.0.8
    with:
      runner: 'ubuntu-22.04' # with ubuntu > 22.04, pip is broken
      python-version-alt1: '3.11'
      python-version-alt2: '3.12'
      python-version: '3.13'
      python-version-alt3: '3.14'
      do-codecov: true
      do-coveralls: false
      do-mypy: true
      alternate-tests-env-files: .ci_support/lower_bound.yml
      alternate-tests-python-version: '3.11'
      alternate-tests-dir: tests/unit
    secrets: inherit
