# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@pyyaml_via_apt
    with:
      python-version-alt3: 'exclude'  # No python 3.9
    secrets: inherit
