# This runs jobs which pyiron modules should run on release
name: Release

on:
  pull_request:
  release:
    types: [ published ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/hatch-release.yml@actions-4.0.9
    secrets: inherit
    with:
      runner: 'ubuntu-22.04' # with ubuntu > 22.04, pip is broken
      semantic-upper-bound: 'minor'
      lower-bound-yaml: '.ci_support/lower_bound.yml'
      publish-to-pypi: ${{ github.event_name == 'release' && github.event.action == 'published' }}
